In [26]:
#Q-1: Create a random 3x4 matrix with value between 0-100. And perform below tasks

x = np.random.randint(0,100,12).reshape(4,3)

In [27]:
import numpy as np

In [28]:
x

array([[13, 84, 56],
       [50, 65,  3],
       [70, 73, 51],
       [59, 73, 57]])

In [29]:
#1) sort the matrix np.sort().

np.sort(x)

array([[13, 56, 84],
       [ 3, 50, 65],
       [51, 70, 73],
       [57, 59, 73]])

In [36]:
#2)  Sort this matrix based on values in 2nd column.x
x[x[:,1].argsort()]



array([[50, 65,  3],
       [70, 73, 51],
       [59, 73, 57],
       [13, 84, 56]])

In [31]:
#3) Sort this matrix based on max value in each row.
x

array([[13, 84, 56],
       [50, 65,  3],
       [70, 73, 51],
       [59, 73, 57]])

In [37]:
print(np.array(sorted(x, key= lambda x: max(x))))

[[50 65  3]
 [70 73 51]
 [59 73 57]
 [13 84 56]]


In [39]:
#4Sort based on elements value.
np.sort(x, axis=None).reshape(4,3)

array([[ 3, 13, 50],
       [51, 56, 57],
       [59, 65, 70],
       [73, 73, 84]])

In [43]:
#Q-2: There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task

marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

In [44]:
np.array(marks)

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [54]:
extra_subject = np.array([41,87,72,36,92]).reshape(-1,1)

In [55]:
extra_subject

array([[41],
       [87],
       [72],
       [36],
       [92]])

In [57]:
#1) Add marks every student of an extra subject in the same array.

#we havr to add extra subject that means we have to add a ro with the given array. But to concatenate
#we have to reshape to the current array.


marks = np.concatenate([marks, extra_subject], axis=1)

In [58]:
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [59]:
#2) ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

In [72]:
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)

In [74]:
rec1

array([[77, 83, 98, 95, 89]])

In [75]:
rec2

array([[92, 71, 52, 61, 53]])

In [76]:
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [78]:
marks = np.concatenate([marks, rec1, rec2], axis =0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [81]:
#3) iii. Add extra column with sum of all subjects(5-subjects) marks

sum_of_student = marks.sum(axis = 1, keepdims = True)

In [82]:
sum_of_student

array([[106],
       [328],
       [229],
       [234],
       [315],
       [442],
       [329],
       [442],
       [329]])

In [84]:
marks = np.concatenate([marks, sum_of_student], axis = 1)

In [85]:
marks


array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [86]:
#iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.#

np.array(sorted(marks, key = lambda x: x[-1], reverse= True))

array([[ 77,  83,  98,  95,  89, 442],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

In [ ]:
#Q-3: Find unique arrays from a 2D array column wise and row wise.

In [89]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [90]:
arr

array([[1, 2, 3, 3, 1, 1],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [93]:
np.unique(arr, axis = 0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [94]:
np.unique(arr, axis = 1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [96]:
#Q-4: Flip given 2-D array along both axes at the same time.
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])


In [101]:
np.flip(arr, axis=[0,1])

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

In [109]:
#Q5Get row numbers of NumPy array having element larger than X.

arr =np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]]) 

x = 6

In [110]:
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [114]:
np.where(np.any(arr>x, axis = 1))

(array([1, 3], dtype=int64),)

In [ ]:
#Q6)How to convert an array of arrays into a flat 1d array?


In [117]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [124]:
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
#Q-7: You are given a array. You have to find the minimum and maximum array element and remove that from the array.

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [127]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [128]:
max_elem = arr.argmax()
min_elem = arr.argmin()

In [131]:
max_elem
min_elem

66

In [132]:
arr  = np.delete(arr, max_elem, axis = 1)
arr = np.delete(arr, min_elem, axis = 1)

In [134]:
arr.shape

(1, 198)

In [135]:
#Q-8: You are given an arrays. You have to limit this array's elements between 100 to 200. 
#arr∈[100,200] . So replace those values accordingly with the minimum and maximum value. 
#Then sort the array and perform the cumulative sum of that array.

In [136]:
arr = np.random.randint(0,200,500)

In [137]:
arr

array([149,  25,  77,  71, 122, 146, 127, 133,  38,  45, 103, 123, 167,
        32, 149,  36,   6,  98, 168, 182,  20,  20,  34, 185, 149, 112,
        57,  55,  33, 122, 174, 179,  37, 100,  20, 142, 188,  80, 180,
        63,  46,  57, 107, 148,  46,  31, 188, 132, 126,  54,  62, 176,
       170, 115,  49, 131,   0,  62, 118,  53,  46, 161,  57,   3,  99,
        98,  11, 138,  92,  97, 138,  49, 113, 167, 135,  23,  28, 137,
       101,  63, 198,  12, 103,  28,  78,  54,  58,  30, 115,  97,   3,
        10, 134,  43,  29, 107,  87, 168, 137, 188,  97, 155, 167,  50,
        25,  94,  25, 199,   2, 149,  85,  46, 184,  60,  21,  28,  37,
       135, 147,  47, 179,  64,  27, 141, 150, 123, 197,  52, 143, 143,
       102, 132,  97, 109,  39, 116,  31, 125, 104,   8,  87,  22,  65,
       161,  43, 133, 152,  77, 128, 166,  51, 132, 153, 188,  53,  48,
       190, 154, 117,   8, 163,  99, 115, 115, 105, 113,  44, 173,   6,
       171,  39, 152, 172, 101,  51, 199, 111, 108, 171,  36, 19

In [140]:
np.cumsum(np.sort(np.clip(arr, 100,200)))

array([  100,   200,   300,   400,   500,   600,   700,   800,   900,
        1000,  1100,  1200,  1300,  1400,  1500,  1600,  1700,  1800,
        1900,  2000,  2100,  2200,  2300,  2400,  2500,  2600,  2700,
        2800,  2900,  3000,  3100,  3200,  3300,  3400,  3500,  3600,
        3700,  3800,  3900,  4000,  4100,  4200,  4300,  4400,  4500,
        4600,  4700,  4800,  4900,  5000,  5100,  5200,  5300,  5400,
        5500,  5600,  5700,  5800,  5900,  6000,  6100,  6200,  6300,
        6400,  6500,  6600,  6700,  6800,  6900,  7000,  7100,  7200,
        7300,  7400,  7500,  7600,  7700,  7800,  7900,  8000,  8100,
        8200,  8300,  8400,  8500,  8600,  8700,  8800,  8900,  9000,
        9100,  9200,  9300,  9400,  9500,  9600,  9700,  9800,  9900,
       10000, 10100, 10200, 10300, 10400, 10500, 10600, 10700, 10800,
       10900, 11000, 11100, 11200, 11300, 11400, 11500, 11600, 11700,
       11800, 11900, 12000, 12100, 12200, 12300, 12400, 12500, 12600,
       12700, 12800,

In [ ]:
#Q-9: You are given a array ( arr∈[0,1] ). First you have round off the elements upto 3 decimal places and compare that
#0th percentile == minimum value of the array
#100th percentile == maximum value of the array
#also find the difference betwen 51th percenile and 50th percentile values

In [141]:
arr = np.random.random(100)

In [142]:
arr

array([0.1879454 , 0.9923638 , 0.28458043, 0.8076621 , 0.93668689,
       0.46494632, 0.77193586, 0.73349003, 0.52767812, 0.78711912,
       0.01988042, 0.14580326, 0.70314929, 0.47456561, 0.32472416,
       0.86278508, 0.48469337, 0.76098456, 0.43266592, 0.06959754,
       0.27370744, 0.70337477, 0.67058162, 0.29853609, 0.30793819,
       0.50707411, 0.72911297, 0.05729163, 0.78376535, 0.08379556,
       0.52712   , 0.67133975, 0.05551574, 0.79734385, 0.5531572 ,
       0.77148727, 0.700605  , 0.96452175, 0.3480317 , 0.03441636,
       0.6755922 , 0.23807503, 0.51330411, 0.57601646, 0.62595249,
       0.55566812, 0.17540318, 0.98697806, 0.83824358, 0.98156015,
       0.95260124, 0.65198182, 0.98659528, 0.58405701, 0.44419804,
       0.16163855, 0.37713326, 0.96466575, 0.78415835, 0.9362919 ,
       0.31415896, 0.14407417, 0.66819943, 0.16241297, 0.10694954,
       0.75798303, 0.52444399, 0.38161244, 0.01388464, 0.71107234,
       0.40254857, 0.80673728, 0.7234179 , 0.82534172, 0.20735

In [148]:
arr = np.around(arr, decimals = 3)

In [149]:
arr

array([0.188, 0.992, 0.285, 0.808, 0.937, 0.465, 0.772, 0.733, 0.528,
       0.787, 0.02 , 0.146, 0.703, 0.475, 0.325, 0.863, 0.485, 0.761,
       0.433, 0.07 , 0.274, 0.703, 0.671, 0.299, 0.308, 0.507, 0.729,
       0.057, 0.784, 0.084, 0.527, 0.671, 0.056, 0.797, 0.553, 0.771,
       0.701, 0.965, 0.348, 0.034, 0.676, 0.238, 0.513, 0.576, 0.626,
       0.556, 0.175, 0.987, 0.838, 0.982, 0.953, 0.652, 0.987, 0.584,
       0.444, 0.162, 0.377, 0.965, 0.784, 0.936, 0.314, 0.144, 0.668,
       0.162, 0.107, 0.758, 0.524, 0.382, 0.014, 0.711, 0.403, 0.807,
       0.723, 0.825, 0.207, 0.973, 0.318, 0.726, 0.963, 0.724, 0.521,
       0.3  , 0.205, 0.263, 0.842, 0.166, 0.224, 0.712, 0.438, 0.831,
       0.049, 0.48 , 0.295, 0.52 , 0.865, 0.844, 0.691, 0.113, 0.183,
       0.868])

In [152]:
np.percentile(arr, 0)== arr.min()

True

In [153]:
np.percentile(arr,100)== arr.max()

True

In [154]:
np.percentile(arr,51)-np.percentile(arr,50)

0.013970000000000038