In [2]:
import numpy as np


In [29]:
#Q-1 Create a null vector of size 10 but the fifth value which is 1.
a = np.nan * np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [3]:
#Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the
#array and avg of the array.

a= int(input("Enter the shape a:"))
b = int(input("enter the shape b:"))

np.random.random((a,b))

Enter the shape a:2
enter the shape b:3


array([[0.48904145, 0.50991342, 0.52036939],
       [0.4865929 , 0.4779483 , 0.08043921]])

In [10]:
#Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as 
#parameter to function.
z = np.ones((4,4))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [18]:
#Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
Z= np.linspace(0,1,10, endpoint=False)
Z

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [24]:
#Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.
# Ans No.

In [27]:
#Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.
Z = np.random.rand(5,5)
Z

array([[0.97491544, 0.72940775, 0.5312659 , 0.18413699, 0.04447165],
       [0.9823567 , 0.30735954, 0.14129054, 0.31735624, 0.96603429],
       [0.13867379, 0.34622528, 0.69639621, 0.06395412, 0.91421191],
       [0.07330528, 0.80553398, 0.92908083, 0.76195388, 0.12588157],
       [0.65741829, 0.91571061, 0.92318867, 0.59835285, 0.46062737]])

In [43]:
#Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates,
#and coordinates of a point as array is given. Create an array of distance of each point in the random vectros 
#from the given point. Distance array should be interger type.

a = np.random.randint(1,100, size=20).reshape((10,2))
p = np.array([2,3]) 

print(a)
print()
print(p)
np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)

[[53 50]
 [21 22]
 [53 62]
 [62 99]
 [54 20]
 [18 70]
 [88 78]
 [ 1 81]
 [62 37]
 [58  9]]

[2 3]


array([ 69,  26,  77, 113,  54,  68, 114,  78,  68,  56])

In [48]:
#Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [50]:
np.zeros((6,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [1]:
#Q-9: Arrays
#You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

In [10]:
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)


2 4 5 6 7


array([7., 6., 5., 4., 2.], dtype=float32)

In [11]:
#10 Elements count
#Count the numbers of elements of a numpy array
np.array([]).size

0

In [13]:
np.array([1,2]).size

2

In [14]:
#Q-11: Softmax function
#Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 
#1D array, otherwise raise error.

a = [1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0]
np.exp(a)/np.sum(np.exp(a))

array([0.02364054, 0.06426166, 0.1746813 , 0.474833  , 0.02364054,
       0.06426166, 0.1746813 ])

In [23]:
b = [86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]

np.exp(b)/np.sum(np.exp(b))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

In [37]:
def softmax(arr):
    if type(arr)!= np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim >1:
            raise TypeError("Requires 1D Array")
    return np.exp(arr)/np.sum(np.exp(arr))

In [34]:
softmax(a)

array([[7.80134161e-05, 2.12062451e-04, 5.76445508e-04, 1.56694135e-03,
        4.25938820e-03],
       [1.15782175e-02, 3.14728583e-02, 8.55520989e-02, 2.32554716e-01,
        6.32149258e-01]])

In [26]:
#Q-12: Vertical stack
#Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. 
#Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

In [46]:
def vstack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

In [47]:
a = np.arange(10).reshape(2,5)
b = np.ones((2,5))
c = np.random.random((2,5))

In [48]:
vstack(a,b)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
vstack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.46134254, 0.66486186, 0.84319906, 0.36073188, 0.9736084 ],
       [0.47607659, 0.33456835, 0.51826471, 0.97330249, 0.94545675]])

In [51]:
d = np.repeat(1,10).reshape(2,5)

In [52]:
d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
#Q-13: Dates
#Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates
#between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this 
#only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year

In [61]:
a =date_array(start='2020-09-15', end = '2020-09-25')



NameError: name 'date_array' is not defined

In [63]:
#Q-14: Subtract the mean of each row from a matrix.

a = np.arange(10).reshape(2,5)

In [64]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
b = np.mean(a, axis=1, keepdims=True)

In [73]:
b

array([[2.],
       [7.]])

In [74]:
a-b

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [76]:
#-Q15: Swap column-1 of array with column-2 in the array.
a = np.arange(9).reshape(3,3)

In [77]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [86]:
#Q-16: Replace odd elements in arrays with -1.
a = np.arange(10) #Example of boolean indexing.

In [92]:
a[a%2==1] = -1

In [93]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [134]:
#Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

In [132]:
a[b>a] = b[a<b]

In [133]:
a

array([6, 3, 1, 7, 8])

In [135]:
b>a

array([False, False, False,  True, False])

In [136]:
a>b

array([ True,  True, False, False,  True])

In [138]:
a

array([6, 3, 1, 5, 8])

In [139]:
#Q-18 Answer below asked questions on given array:
#Fetch Every alternate column of the array
#Normalise the given array

In [140]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)

In [141]:
arr1

array([[8260, 1174, 4868, 5686, 1295],
       [8044, 8577, 7579, 4577,  155],
       [7910, 6048, 1403, 4854, 5838],
       [2533, 7289, 7489, 1655, 8996],
       [ 633, 3772, 7318, 4174, 7963],
       [2684, 1758, 7602, 5264, 8824],
       [8068, 4567, 1745,  249, 5184],
       [4137, 7457, 9600,  618, 5602]])

In [143]:
arr1[:,::2]

array([[8260, 4868, 1295],
       [8044, 7579,  155],
       [7910, 1403, 5838],
       [2533, 7489, 8996],
       [ 633, 7318, 7963],
       [2684, 7602, 8824],
       [8068, 1745, 5184],
       [4137, 9600, 5602]])

In [146]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.85812599, 0.10788777, 0.49899418, 0.58560085, 0.12069878],
       [0.83525675, 0.89168872, 0.78602435, 0.46818422, 0.        ],
       [0.82106935, 0.623928  , 0.1321334 , 0.49751191, 0.60169402],
       [0.25177343, 0.75532028, 0.7764955 , 0.15881419, 0.93605082],
       [0.05060879, 0.38295394, 0.75839068, 0.42551615, 0.82668078],
       [0.26776072, 0.16971943, 0.7884595 , 0.54092112, 0.91784013],
       [0.83779778, 0.46712546, 0.16834304, 0.00995236, 0.53245103],
       [0.42159873, 0.77310746, 1.        , 0.04902065, 0.57670725]])

In [161]:
#Q-19: Write a function which will accept 2 arguments.
#First: A 1D numpy array arr

#Second: An integer n {Please make sure n<=len(arr)}

#Output: The output should be the nth largest item out of the array

def n_lar_number(arr,n):
    if n > len(arr):
        raise IndexErrorError(" n should be less than equal to len(arr)")
    arr.sort()
    return arr[-n]
n_lar_number(np.array([12,34,40,7,1,0]),2)
    

34

In [162]:
#Q-20: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [155]:
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [168]:
a = np.array([1,2,3])
np.repeat(a, 3)
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [169]:
np.hstack([np.repeat(a,3), np.tile(a,3)])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])